# Generated by Django 4.0.6 on 2022-07-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('imei', models.CharField(max_length=250)),
                ('created', models.DateField(auto_now_add=True)),
                ('date_of_purchase', models.DateField(null=True)),
                ('client', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('defect', models.TextField()),
                ('comment', models.TextField(default='used')),
                ('full_set', models.TextField(default='full seet')),
                ('warranty', models.BooleanField(default=False)),
                ('cheque', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=250)),
                ('status_updated', models.DateField(auto_now=True)),
                ('delta_expiring', models.IntegerField(default=0)),
                ('delta_shop_hold', models.IntegerField(default=0)),
                ('delta_pending', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryShopHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('imei', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('model', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryLineShopHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_link_number', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_items.item')),
                ('registry_shop_hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_items.registryshophold')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, max_length=250)),
                ('user', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('model', models.CharField(blank=True, max_length=250)),
                ('imei', models.CharField(blank=True, max_length=250)),
                ('date_of_delivery', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(auto_now_add=True)),
                ('date_of_purchase', models.DateField(null=True)),
                ('client', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('defect', models.TextField()),
                ('comment', models.TextField(default='used')),
                ('full_set', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_items.registry')),
            ],
        ),
    ]
