# Generated by Django 3.1 on 2020-10-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cheque',
            field=models.BooleanField(default=False),
        ),
    ]
