# Generated by Django 3.1 on 2020-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
