# Generated by Django 3.1 on 2021-01-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrylinepending',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='client',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='created',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='date_of_delivery',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='defect',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='full_set',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='model',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registrylinepending',
            name='user',
        ),
        migrations.AddField(
            model_name='registrylinepending',
            name='item_link_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_items.item'),
        ),
    ]
