# Generated by Django 3.1 on 2020-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0002_auto_20201012_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
