# Generated by Django 3.1 on 2020-10-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0002_item_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registryline',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='registryline',
            name='warranty',
        ),
    ]
