# Generated by Django 3.1 on 2020-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0003_auto_20201012_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
