# Generated by Django 4.0.6 on 2023-11-01 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_supplier'),
        ('app_items', '0004_item_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
