# Generated by Django 3.1 on 2020-10-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0004_item_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryLinePeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, max_length=250)),
                ('user', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('model', models.CharField(blank=True, max_length=250)),
                ('imei', models.CharField(blank=True, max_length=250)),
                ('date_of_delivery', models.CharField(blank=True, max_length=250)),
                ('created', models.DateField(auto_now_add=True)),
                ('date_of_purchase', models.DateField(null=True)),
                ('client', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('defect', models.TextField()),
                ('comment', models.TextField(default='used')),
                ('full_set', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('registry_pending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_items.registrypending')),
            ],
        ),
    ]
