# Generated by Django 3.1 on 2021-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0004_auto_20210113_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delta_expiring',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='delta_pending',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='delta_shop_hold',
            field=models.IntegerField(default=0),
        ),
    ]
