# Generated by Django 3.1 on 2021-01-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0005_auto_20210113_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrylineexpiring',
            name='item_link_number',
        ),
        migrations.RemoveField(
            model_name='registrylineexpiring',
            name='registry_expiring',
        ),
        migrations.DeleteModel(
            name='RegistryExpiring',
        ),
        migrations.DeleteModel(
            name='RegistryLineExpiring',
        ),
    ]
