# Generated by Django 3.1 on 2020-10-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0005_registrylinepeding_registrypending'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistryLinePeding',
            new_name='RegistryLinePending',
        ),
    ]
