# Generated by Django 3.1 on 2020-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0006_auto_20201013_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_change', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('imei', models.CharField(blank=True, max_length=250)),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('model', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
