# Generated by Django 3.1 on 2021-01-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0006_auto_20210113_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistryLinePending',
        ),
        migrations.DeleteModel(
            name='RegistryPending',
        ),
    ]
