# Generated by Django 3.1 on 2020-10-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0008_registryexpiring_registrylineexpiring_registrylineshophold_registryshophold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrylineshophold',
            old_name='registry_pending',
            new_name='registry_shop_hold',
        ),
    ]
